# -*- coding: utf-8 -*-
"""StableDiffusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13x5cANQPO2iWAQTJSombpdYb47f8cJy0
"""

!pip install torch diffusers transformers accelerate

import torch
from diffusers import StableDiffusionPipeline

# Check if CUDA is available and set the device
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load the Stable Diffusion pipeline
model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id)
pipe = pipe.to(device)

def generate_image(prompt, filename, steps=50, guidance=7.5, height=512, width=512, neg_prompt=None, num_images=1, seed=None):
    generator = torch.Generator(device=device).manual_seed(seed) if seed else None

    images = pipe(
        prompt,
        height=height,
        width=width,
        num_inference_steps=steps,
        guidance_scale=guidance,
        negative_prompt=neg_prompt,
        num_images_per_prompt=num_images,
        generator=generator
    ).images

    for i, image in enumerate(images):
        image.save(f"{filename}_{i}.png")
        print(f"Image saved as {filename}_{i}.png")

# Example usage
generate_image(
    prompt="A serene mountain landscape with a calm lake reflecting the sunset sky",
    filename="mountain_landscape",
    steps=20,
    guidance=8.0,
    height=768,
    width=512,
    neg_prompt="clouds, hazy",
    num_images=1,
    seed=42
)

